// GENERATED by scripts/gen-agent-packs.js — do not edit.
// Regenerate: node scripts/gen-agent-packs.js  (test/packs.test.js enforces freshness)
export const PACKS = {
 "version": "v0.10.0",
 "tabs": {
  "Balance": {
   "name": "Balance",
   "summary": "The difficulty scaling matrix: every `DEFAULTS` constant in one flat knob\nlist — tick rate, tap, unit costs/growth/rate/noise, mult thresholds,\nupgrade costs, loom, stir, belief, notes, tiptoe, night/contracts, stars,\nsky, constellations.",
   "visual": "One section per top-level `DEFAULTS` key, each a flat list of path → input\nrows with the default shown alongside and a reset button. Changed rows are\nhighlighted.",
   "files": "js/dev/panel.js (tabBalance), js/config/constants.js, js/engine/*",
   "capabilities": "Find or explain any balance constant by path, and change it live — edits\nwrite straight into the running engine's config and persist as an\noverride. Numeric edits are rejected (shown red), never silently clamped:\na positive default never accepts zero or less. New constants, new engine\nmechanics, or anything touching js/engine/* logic go to the prompt package.",
   "hotkeys": "None specific to this tab."
  },
  "Hoard": {
   "name": "Hoard",
   "summary": "Tier-by-tier stash preview: sack, jars, chests, piles, warehouses, silos,\nmountains, moons. Pick a tier to preview it on the banner, scrub the tooth\ncount within it, and tune its shape knobs alongside whole-hoard knobs.",
   "visual": "A strip of tier buttons across the top, then a scrub slider (with an \"∞\"\nbutton on the last tier and a \"live\" button to return to the real count),\nthen \"this tier\" sliders (units, px) and \"whole hoard\" sliders below.",
   "files": "js/dev/panel.js (tabHoard), js/dev/knob-ranges.js, js/config/vfx.js (hoard), js/ui/hoard.js, js/ui/stage.js",
   "capabilities": "Preview any tier at any count and tune its `units`/`px` shape, plus the\nshared hoard knobs (alpha, glintPerS, centerGapPx, stageScale, stageAlpha).\nPreview never touches game state. Save-to-project and release live on the\nWorkshop tab and need the local workshop server — not available in the\nartifact; route code/commit requests to the prompt package.",
   "hotkeys": "None specific to this tab; the panel's `[`/`]` and Shift+1..8 tab-switch\nhotkeys still apply."
  },
  "Names": {
   "name": "Names",
   "summary": "Every player-visible label outside the story script: unit names/flavor,\nupgrade names/flavor, sky card names/flavor, constellation names/flavor,\nhoard tier labels, UI strings, meter labels, and tooltip copy.",
   "visual": "A flat list of path → text-input rows per top-level `NAME_DEFAULTS` key\n(units, upgrades, sky, constellations, hoard, ui, tips, ...), default shown\nalongside, reset button per row.",
   "files": "js/dev/panel.js (tabNames), js/config/names.js",
   "capabilities": "Find or rename any player-visible label live; edits persist as an\noverride. Renames need a reload before they show up on shop cards, which\nare built once at boot. New UI surfaces that need new label keys go to the\nprompt package.",
   "hotkeys": "None specific to this tab."
  },
  "Pacing": {
   "name": "Pacing",
   "summary": "Runs the real engine headless, driven by a competent-not-optimal bot, using\nthe current live-tuned balance and script — not a model, the same tick the\ngame runs. Reports act timing, reveal cadence, story beats hit, dead time,\nand unreached beats.",
   "visual": "A seed number field, a taps-per-tick preset (casual / fast / idle), and a\nrun button. The report below shows a summary line, a reveal-cadence table\n(gaps under 3s flagged), a story-beats table, and any unreached beats.",
   "files": "js/dev/panel.js (tabPacing), js/dev/bot.js",
   "capabilities": "Run a full headless playthrough against live balance/script tuning and\nread back its pacing report to spot dead time, crowded reveals, or beats\nthe bot never reaches. It does not change any knob itself — it is a\nreadout. Bot policy or engine changes go to the prompt package.",
   "hotkeys": "None specific to this tab."
  },
  "Script": {
   "name": "Script",
   "summary": "The story data: beats (trigger, text, response, register), asides,\nper-act whispers, and the children's notes. Each beat has an id, act,\nregister ('memory' or 'ledger'), trigger JSON, and optional effects.",
   "visual": "A scrollable list of beat editors (id, trigger JSON field, ▶ play button,\nduplicate button, text area, response + register fields), then an asides\nlist, then one whisper textarea per act, then a single notes textarea.",
   "files": "js/dev/panel.js (tabScript), js/config/script.js",
   "capabilities": "Script edits are text edits, not knobs: this agent helps find beats (by id,\ntrigger type, or act) and explains trigger/effect shapes, and can point at\nwhat to duplicate or arm for ▶ play. Edits made in-page apply live and\npersist as overrides; duplicated beats are born dormant (trigger `never`)\nuntil armed. Structural changes — new trigger types, new effect kinds, new\nbeats wired into code — go to the prompt package.",
   "hotkeys": "None; navigate the beat/aside/whisper lists by scrolling."
  },
  "State": {
   "name": "State",
   "summary": "Direct engine control: grant teeth/stars, drag belief/stir meters, jump to\nan act (including 2.5), skip to dawn/dusk, advance time, simulate 8h\noffline, reload at a speed multiplier, and a live JSON view of state.",
   "visual": "Grant buttons (+teeth amounts, +10★, start autopilot), belief/stir range\nsliders, act-jump buttons, dawn/dusk skip buttons, time-advance and\noffline-simulate buttons, speed-reload buttons, and a live-refreshing JSON\n`<pre>` of the current state snapshot.",
   "files": "js/dev/panel.js (tabState), js/engine/actions.js (dev actions)",
   "capabilities": "Grant resources, force meters, jump acts, skip to dawn/dusk, advance time,\nand simulate offline play — all live engine dispatches. Speed reload does\nnot work inside the artifact (no URL params to reload against); everything\nelse on this tab works normally. New dev actions go to the prompt package.",
   "hotkeys": "None specific to this tab."
  },
  "Dev Suite": {
   "name": "Dev Suite",
   "summary": "The overview agent for the whole Dev Suite. One line per tab: Workshop\ntunes juice/vfx sliders with live preview; Hoard previews stash tiers;\nScript edits story beats/asides/whispers/notes; Balance tunes the\ndifficulty matrix; Names edits every player-visible label; VFX tunes the\nrest of the visual/audio knobs; State grants resources and jumps engine\nstate; Pacing runs a headless bot playthrough report.",
   "visual": "A row of tab buttons across the top (Workshop, Hoard, Script, Balance,\nNames, VFX, State, Pacing), a chat panel that toggles with backquote, and\nthe game itself always visible so changes are seen immediately.",
   "files": "js/dev/panel.js, js/dev/knob-ranges.js, js/dev/ovstore.js, js/config/constants.js, js/config/names.js, js/config/vfx.js, js/config/script.js",
   "capabilities": "Route a request to a per-tab agent when it names or clearly targets one\ntab's knobs; otherwise answer here — orient the user, explain how\noverrides work, or point at \"copy all overrides\". Overrides are a live\nobject merged with a localStorage diff over frozen defaults: only changed\nkeys persist. \"Copy all overrides\" copies that diff as JSON; paste it into\nthe matching `js/config/*.js` file's defaults to commit a tuning\npermanently. Code changes, new features, and anything structural go to the\nprompt package, not any dev-suite agent.",
   "hotkeys": "| Keys | Action |\n| --- | --- |\n| `[` / `]` | Cycle dev tabs |\n| Shift+1..8 | Direct-select tab (Workshop, Hoard, Script, Balance, Names, VFX, State, Pacing) |\n| Backquote | Toggle the chat (raise focuses input) |\n| Esc | Dismiss the chat |\n| Ctrl+ArrowLeft / Ctrl+ArrowRight | Switch chat tabs |\n| Enter / Shift+Enter | Submit chat message / newline in chat |\n| 1-5, A, R | Workshop preview keys — active only while the Workshop tab is shown |\n\nGame hotkeys are disabled in the artifact."
  },
  "VFX": {
   "name": "VFX",
   "summary": "Visual and audio tuning beyond the Workshop's juice sliders: motif, pulse,\nfloats, beat timing, ceremony, wake flash, sky twinkle, palettes,\nconstellation point/edge geometry, and sound gains per cue.",
   "visual": "A \"test sounds\" button that plays each cue in sequence, then a flat knob\nlist (same row style as Balance/Names) walking every `VFX_DEFAULTS` key.",
   "files": "js/dev/panel.js (tabVfx), js/config/vfx.js, js/ui/sound.js",
   "capabilities": "Find or tune any visual/audio knob live, including sound gains (`sound.tap`,\n`sound.fill`, etc.); edits persist as an override. New sound cues, new\npalette acts, or new visual systems go to the prompt package.",
   "hotkeys": "None specific to this tab."
  },
  "Workshop": {
   "name": "Workshop",
   "summary": "The juice studio. Live sliders for tap pop, glow, sparks, incoming-teeth\ntrails, landing sparks, powerup sweep, and the scale ramp. Preview buttons\nfire the real feedback paths without playing.",
   "visual": "Sticky preview bar on top (tap / powerup / three flow rates / sequence /\nrepeat toggle), then slider groups. The game stays visible on the right;\nevery slider change auto-fires its group's preview.",
   "files": "js/dev/panel.js (tabWorkshop), js/dev/knob-ranges.js, js/config/vfx.js, js/ui/juice.js, js/ui/conveyor.js",
   "capabilities": "Tune any vfx knob live; preview effects; overrides persist and export via\n\"copy all overrides\". Save-to-project and release need the local workshop\nserver and do not work inside the artifact — route code/commit requests to\nthe prompt package instead.",
   "hotkeys": "1-5 preview actions, A sequence, R repeat — active while this tab is shown."
  }
 },
 "knobs": [
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "TICK_MS"
   ],
   "def": 200
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "TAP",
    "BASE"
   ],
   "def": 1
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "TAP",
    "MAX_PER_TICK"
   ],
   "def": 2
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UNITS",
    "scout",
    "base"
   ],
   "def": 50
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UNITS",
    "scout",
    "growth"
   ],
   "def": 1.15
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UNITS",
    "scout",
    "rate"
   ],
   "def": 1
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UNITS",
    "scout",
    "noise"
   ],
   "def": 0.5
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UNITS",
    "mouse",
    "base"
   ],
   "def": 600
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UNITS",
    "mouse",
    "growth"
   ],
   "def": 1.14
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UNITS",
    "mouse",
    "rate"
   ],
   "def": 10
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UNITS",
    "mouse",
    "noise"
   ],
   "def": 1.5
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UNITS",
    "bunny",
    "base"
   ],
   "def": 5000
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UNITS",
    "bunny",
    "growth"
   ],
   "def": 1.14
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UNITS",
    "bunny",
    "rate"
   ],
   "def": 60
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UNITS",
    "bunny",
    "noise"
   ],
   "def": 3
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UNITS",
    "sprite",
    "base"
   ],
   "def": 2500
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UNITS",
    "sprite",
    "growth"
   ],
   "def": 1.05
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UNITS",
    "sprite",
    "rate"
   ],
   "def": 40
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UNITS",
    "sprite",
    "noise"
   ],
   "def": 6
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UNITS",
    "sprite",
    "lifeTicks"
   ],
   "def": 450
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UNITS",
    "sprite",
    "afterglowFrac"
   ],
   "def": 0.5
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UNITS",
    "sprite",
    "swarmCap"
   ],
   "def": 8
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UNITS",
    "sprite",
    "capPerMult"
   ],
   "def": 4
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UNITS",
    "phantom",
    "base"
   ],
   "def": 12000
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UNITS",
    "phantom",
    "growth"
   ],
   "def": 1.13
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UNITS",
    "phantom",
    "rate"
   ],
   "def": 120
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UNITS",
    "phantom",
    "noise"
   ],
   "def": 0
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UNITS",
    "owl",
    "base"
   ],
   "def": 45000
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UNITS",
    "owl",
    "growth"
   ],
   "def": 1.13
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UNITS",
    "owl",
    "rate"
   ],
   "def": 300
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UNITS",
    "owl",
    "noise"
   ],
   "def": 0.2
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UNITS",
    "ferry",
    "base"
   ],
   "def": 140000
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UNITS",
    "ferry",
    "growth"
   ],
   "def": 1.12
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UNITS",
    "ferry",
    "rate"
   ],
   "def": 0
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UNITS",
    "ferry",
    "noise"
   ],
   "def": 0.3
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UNITS",
    "ferry",
    "lumpAmount"
   ],
   "def": 12000
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UNITS",
    "ferry",
    "lumpEveryTicks"
   ],
   "def": 60
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UNITS",
    "ferry",
    "noiseSpike"
   ],
   "def": 6
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UNITS",
    "barge",
    "base"
   ],
   "def": 400000
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UNITS",
    "barge",
    "growth"
   ],
   "def": 1.18
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UNITS",
    "barge",
    "rate"
   ],
   "def": 0
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UNITS",
    "barge",
    "noise"
   ],
   "def": 0.5
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UNITS",
    "barge",
    "manifestFrac"
   ],
   "def": 0.05
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UNITS",
    "barge",
    "manifestCap"
   ],
   "def": 0.25
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UNITS",
    "pact",
    "base"
   ],
   "def": 1200000
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UNITS",
    "pact",
    "growth"
   ],
   "def": 1.22
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UNITS",
    "pact",
    "rate"
   ],
   "def": 6000
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UNITS",
    "pact",
    "noise"
   ],
   "def": 0
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UNITS",
    "pact",
    "stirFactor"
   ],
   "def": 0.96
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UNITS",
    "pact",
    "netBonusPer"
   ],
   "def": 0.01
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UNITS",
    "pact",
    "netBonusCap"
   ],
   "def": 3
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UNITS",
    "ministry",
    "base"
   ],
   "def": 40000000
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UNITS",
    "ministry",
    "growth"
   ],
   "def": 1.22
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UNITS",
    "ministry",
    "rate"
   ],
   "def": 60000
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UNITS",
    "ministry",
    "noise"
   ],
   "def": 0
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UNITS",
    "starwrights",
    "base"
   ],
   "def": 400000000
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UNITS",
    "starwrights",
    "growth"
   ],
   "def": 1.25
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UNITS",
    "starwrights",
    "rate"
   ],
   "def": 1000000
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UNITS",
    "starwrights",
    "noise"
   ],
   "def": 0
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "MULT_THRESHOLDS",
    0
   ],
   "def": 10
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "MULT_THRESHOLDS",
    1
   ],
   "def": 25
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "MULT_THRESHOLDS",
    2
   ],
   "def": 50
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "MULT_COST_FACTOR"
   ],
   "def": 12
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UPGRADES",
    "babyfae",
    "cost"
   ],
   "def": 25
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UPGRADES",
    "pincers",
    "cost"
   ],
   "def": 400
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UPGRADES",
    "tweezers",
    "cost"
   ],
   "def": 5000
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UPGRADES",
    "gloves",
    "cost"
   ],
   "def": 60000
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UPGRADES",
    "starlight",
    "cost"
   ],
   "def": 750000
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UPGRADES",
    "starlight",
    "tapRateFrac"
   ],
   "def": 0.01
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UPGRADES",
    "afterglow",
    "cost"
   ],
   "def": 9000
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UPGRADES",
    "sandman",
    "cost"
   ],
   "def": 30000
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UPGRADES",
    "dreamledger",
    "cost"
   ],
   "def": 800
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UPGRADES",
    "dreamledger",
    "offlineRate"
   ],
   "def": 0.5
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UPGRADES",
    "dreamledger",
    "offlineCapHours"
   ],
   "def": 2
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UPGRADES",
    "nightledger",
    "cost"
   ],
   "def": 150000
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UPGRADES",
    "nightledger",
    "offlineCapHours"
   ],
   "def": 8
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UPGRADES",
    "lucidcontract",
    "cost"
   ],
   "def": 5000000
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UPGRADES",
    "lucidcontract",
    "offlineRate"
   ],
   "def": 1
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UPGRADES",
    "lucidcontract",
    "offlineCapHours"
   ],
   "def": 24
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UPGRADES",
    "sockradar",
    "cost"
   ],
   "def": 12000
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UPGRADES",
    "sockradar",
    "unitMult"
   ],
   "def": "scout"
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UPGRADES",
    "madrid",
    "cost"
   ],
   "def": 90000
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UPGRADES",
    "madrid",
    "unitMult"
   ],
   "def": "mouse"
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UPGRADES",
    "encore",
    "cost"
   ],
   "def": 60000
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UPGRADES",
    "encore",
    "spriteLifeMult"
   ],
   "def": 1.5
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UPGRADES",
    "feltslippers",
    "cost"
   ],
   "def": 300000
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UPGRADES",
    "feltslippers",
    "unitMult"
   ],
   "def": "phantom"
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UPGRADES",
    "lighthouse",
    "cost"
   ],
   "def": 900000
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UPGRADES",
    "lighthouse",
    "unitMult"
   ],
   "def": "ferry"
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UPGRADES",
    "manifestii",
    "cost"
   ],
   "def": 2500000
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UPGRADES",
    "manifestii",
    "manifestMult"
   ],
   "def": 2
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UPGRADES",
    "notary",
    "cost"
   ],
   "def": 12000000
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UPGRADES",
    "notary",
    "unitMult"
   ],
   "def": "pact"
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UPGRADES",
    "annexforms",
    "cost"
   ],
   "def": 90000000
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UPGRADES",
    "annexforms",
    "unitMult"
   ],
   "def": "ministry"
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "UPGRADES",
    "moonclippers",
    "cost"
   ],
   "def": 3000000
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "LOOM",
    "base"
   ],
   "def": 4000
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "LOOM",
    "growth"
   ],
   "def": 1.95
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "LOOM",
    "hushPerLevel"
   ],
   "def": 20
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "LOOM",
    "hushFalloff"
   ],
   "def": 0.85
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "STIR",
    "HUSH_BASE"
   ],
   "def": 10
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "STIR",
    "RATE"
   ],
   "def": 0.3
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "STIR",
    "FALL_RATE"
   ],
   "def": 1.5
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "STIR",
    "WAKE_AT"
   ],
   "def": 100
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "STIR",
    "WAKE_BELIEF_COST"
   ],
   "def": 10
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "STIR",
    "WAKE_RESET"
   ],
   "def": 25
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "STIR",
    "STUN_TICKS"
   ],
   "def": 50
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "STIR",
    "SETTLE_TICKS"
   ],
   "def": 150
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "STIR",
    "FIRST_WAKE_AT"
   ],
   "def": 55
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "STIR",
    "REVEAL_NOISE"
   ],
   "def": 20
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "STIR",
    "SCALE_NOISE_PER_LOG10"
   ],
   "def": 13
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "STIR",
    "SCALE_NOISE_FREE_LOG10"
   ],
   "def": 2.6
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "BELIEF",
    "START"
   ],
   "def": 50
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "BELIEF",
    "DRIFT_PER_S"
   ],
   "def": 0.002
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "BELIEF",
    "STREAK_PER_S"
   ],
   "def": 0.05
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "BELIEF",
    "STREAK_CAP"
   ],
   "def": 75
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "BELIEF",
    "NOTE_VALUE"
   ],
   "def": 2
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "NOTES",
    "EVERY_S"
   ],
   "def": 45
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "NOTES",
    "CAP"
   ],
   "def": 12
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "TIPTOE",
    "FACTOR"
   ],
   "def": 0.5
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "TIPTOE",
    "TICKS"
   ],
   "def": 75
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "TIPTOE",
    "SANDMAN_AT"
   ],
   "def": 85
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "OFFLINE",
    "MAX_STEPS"
   ],
   "def": 10000
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "ENDING",
    "LIFETIME"
   ],
   "def": 600000000000
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "OUTLINE",
    "MAX_SIZE"
   ],
   "def": 64
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "OUTLINE",
    "HELPER_FILL_CAP"
   ],
   "def": 6
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "NIGHT",
    "LENGTH_TICKS"
   ],
   "def": 10500
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "NIGHT",
    "MIN_GAP_S"
   ],
   "def": 7200
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "NIGHT",
    "LEDGER_CAP"
   ],
   "def": 30
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "CONTRACTS",
    "PER_NIGHT"
   ],
   "def": 3
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "CONTRACTS",
    "STREAK_TIERS",
    0
   ],
   "def": 3
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "CONTRACTS",
    "STREAK_TIERS",
    1
   ],
   "def": 7
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "CONTRACTS",
    "STREAK_TIERS",
    2
   ],
   "def": 14
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "CONTRACTS",
    "STREAK_MULTS",
    0
   ],
   "def": 1.03
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "CONTRACTS",
    "STREAK_MULTS",
    1
   ],
   "def": 1.05
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "CONTRACTS",
    "STREAK_MULTS",
    2
   ],
   "def": 1.08
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "STARS",
    "PIVOT"
   ],
   "def": 600000000000
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "STARS",
    "AT_PIVOT"
   ],
   "def": 10
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "STARS",
    "EXP"
   ],
   "def": 0.5
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "STARS",
    "RATE_PER_STAR"
   ],
   "def": 0.02
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "STARS",
    "TOWN_LEDGER_CAP"
   ],
   "def": 10
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "SKY",
    "oldroads",
    "cost"
   ],
   "def": 3
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "SKY",
    "mouseletter",
    "cost"
   ],
   "def": 5
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "SKY",
    "mouseletter",
    "scouts"
   ],
   "def": 10
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "SKY",
    "packedlight",
    "cost"
   ],
   "def": 8
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "SKY",
    "lullabythread",
    "cost"
   ],
   "def": 10
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "SKY",
    "lullabythread",
    "hush"
   ],
   "def": 20
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "SKY",
    "starcharts",
    "cost"
   ],
   "def": 12
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "SKY",
    "ferrytoken",
    "cost"
   ],
   "def": 18
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "SKY",
    "ferrytoken",
    "cap"
   ],
   "def": 0.05
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "CONSTELLATIONS",
    "littlest",
    "slots"
   ],
   "def": 4
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "CONSTELLATIONS",
    "littlest",
    "departBonus"
   ],
   "def": 1
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "CONSTELLATIONS",
    "fieldmouse",
    "slots"
   ],
   "def": 6
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "CONSTELLATIONS",
    "fieldmouse",
    "tapMult"
   ],
   "def": 2
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "CONSTELLATIONS",
    "quietloom",
    "slots"
   ],
   "def": 8
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "CONSTELLATIONS",
    "quietloom",
    "noiseFactor"
   ],
   "def": 0.9
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "CONSTELLATIONS",
    "ferryman",
    "slots"
   ],
   "def": 10
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "CONSTELLATIONS",
    "ferryman",
    "gapFactor"
   ],
   "def": 0.5
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "CONSTELLATIONS",
    "toothfairy",
    "slots"
   ],
   "def": 14
  },
  {
   "tab": "Balance",
   "ovKey": "constants",
   "path": [
    "CONSTELLATIONS",
    "toothfairy",
    "rateBonus"
   ],
   "def": 0.01
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "units",
    "scout",
    "name"
   ],
   "def": "TOOTH SCOUT"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "units",
    "scout",
    "flavor"
   ],
   "def": "checks under pillows. mostly finds socks."
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "units",
    "mouse",
    "name"
   ],
   "def": "PILLOW MOUSE"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "units",
    "mouse",
    "flavor"
   ],
   "def": "an old colleague from madrid. very professional."
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "units",
    "bunny",
    "name"
   ],
   "def": "DUST BUNNY"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "units",
    "bunny",
    "flavor"
   ],
   "def": "lives under the bed. always has. finally on payroll."
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "units",
    "sprite",
    "name"
   ],
   "def": "MAYFLY SPRITE"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "units",
    "sprite",
    "flavor"
   ],
   "def": "burns bright. burns out. knows it. does not care."
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "units",
    "phantom",
    "name"
   ],
   "def": "FLOSS PHANTOM"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "units",
    "phantom",
    "flavor"
   ],
   "def": "makes no sound at all. charges accordingly."
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "units",
    "owl",
    "name"
   ],
   "def": "ATTIC OWL"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "units",
    "owl",
    "flavor"
   ],
   "def": "sees everything. says nothing. bills monthly."
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "units",
    "ferry",
    "name"
   ],
   "def": "TOOTH FERRY"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "units",
    "ferry",
    "flavor"
   ],
   "def": "yes, it is spelled like that. no, nobody laughs anymore."
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "units",
    "barge",
    "name"
   ],
   "def": "MOLAR BARGE"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "units",
    "barge",
    "flavor"
   ],
   "def": "sails at dawn with the night's manifest. pays on return."
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "units",
    "pact",
    "name"
   ],
   "def": "PARENT PACT"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "units",
    "pact",
    "flavor"
   ],
   "def": "they were doing it anyway. now it is official."
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "units",
    "ministry",
    "name"
   ],
   "def": "MINISTRY OF MOLARS"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "units",
    "ministry",
    "flavor"
   ],
   "def": "form 32-b: request for additional night."
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "units",
    "starwrights",
    "name"
   ],
   "def": "STARWRIGHTS"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "units",
    "starwrights",
    "flavor"
   ],
   "def": "they take the teeth upstairs. don't ask about the ladder."
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "upgrades",
    "babyfae",
    "name"
   ],
   "def": "BABY FAE"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "upgrades",
    "babyfae",
    "flavor"
   ],
   "def": "small. eager. counts on her fingers. two per tap now."
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "upgrades",
    "pincers",
    "name"
   ],
   "def": "POLISHED PINCERS"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "upgrades",
    "pincers",
    "flavor"
   ],
   "def": "the grip of a professional."
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "upgrades",
    "tweezers",
    "name"
   ],
   "def": "SILVER TWEEZERS"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "upgrades",
    "tweezers",
    "flavor"
   ],
   "def": "surgical. gleaming. slightly show-offy."
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "upgrades",
    "gloves",
    "name"
   ],
   "def": "MOONLIT GLOVES"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "upgrades",
    "gloves",
    "flavor"
   ],
   "def": "woven from the quiet part of the night."
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "upgrades",
    "starlight",
    "name"
   ],
   "def": "STARLIGHT FINGERS"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "upgrades",
    "starlight",
    "flavor"
   ],
   "def": "each tap borrows a little from the whole operation."
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "upgrades",
    "afterglow",
    "name"
   ],
   "def": "AFTERGLOW"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "upgrades",
    "afterglow",
    "flavor"
   ],
   "def": "a sprite that ends well leaves something behind."
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "upgrades",
    "sandman",
    "name"
   ],
   "def": "SANDMAN CONTRACT"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "upgrades",
    "sandman",
    "flavor"
   ],
   "def": "he tiptoes so you do not have to."
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "upgrades",
    "dreamledger",
    "name"
   ],
   "def": "DREAM LEDGER"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "upgrades",
    "dreamledger",
    "flavor"
   ],
   "def": "the night keeps its own books while you are gone."
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "upgrades",
    "nightledger",
    "name"
   ],
   "def": "NIGHT LEDGER"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "upgrades",
    "nightledger",
    "flavor"
   ],
   "def": "a bigger book. a longer night."
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "upgrades",
    "lucidcontract",
    "name"
   ],
   "def": "LUCID CONTRACT"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "upgrades",
    "lucidcontract",
    "flavor"
   ],
   "def": "the dream signs for itself now."
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "upgrades",
    "sockradar",
    "name"
   ],
   "def": "SOCK RADAR"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "upgrades",
    "sockradar",
    "flavor"
   ],
   "def": "filters the false positives. scouts weep with gratitude."
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "upgrades",
    "madrid",
    "name"
   ],
   "def": "MADRID CONNECTIONS"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "upgrades",
    "madrid",
    "flavor"
   ],
   "def": "she made some calls. do not ask on which phone."
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "upgrades",
    "encore",
    "name"
   ],
   "def": "ENCORE"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "upgrades",
    "encore",
    "flavor"
   ],
   "def": "the mayflies negotiated a longer forever."
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "upgrades",
    "feltslippers",
    "name"
   ],
   "def": "FELT SLIPPERS"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "upgrades",
    "feltslippers",
    "flavor"
   ],
   "def": "the phantoms were already silent. now they are smug about it."
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "upgrades",
    "lighthouse",
    "name"
   ],
   "def": "LIGHTHOUSE MOTH"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "upgrades",
    "lighthouse",
    "flavor"
   ],
   "def": "guides the ferries. paid in porchlight."
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "upgrades",
    "manifestii",
    "name"
   ],
   "def": "MANIFEST, PART II"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "upgrades",
    "manifestii",
    "flavor"
   ],
   "def": "the barge found a second hold. do not ask where."
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "upgrades",
    "notary",
    "name"
   ],
   "def": "NIGHT NOTARY"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "upgrades",
    "notary",
    "flavor"
   ],
   "def": "stamps twice. legally distinct thumps."
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "upgrades",
    "annexforms",
    "name"
   ],
   "def": "ANNEX FORMS"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "upgrades",
    "annexforms",
    "flavor"
   ],
   "def": "form 32-c: request for additional additional night."
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "upgrades",
    "moonclippers",
    "name"
   ],
   "def": "MOON CLIPPERS"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "upgrades",
    "moonclippers",
    "flavor"
   ],
   "def": "crescent-shaped. self-sharpening. taps twice as deep."
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "sky",
    "oldroads",
    "name"
   ],
   "def": "OLD ROADS"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "sky",
    "oldroads",
    "flavor"
   ],
   "def": "the first two rungs of the ladder, remembered."
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "sky",
    "mouseletter",
    "name"
   ],
   "def": "A LETTER FROM MADRID"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "sky",
    "mouseletter",
    "flavor"
   ],
   "def": "ten scouts, waiting at the new place. she wrote ahead."
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "sky",
    "packedlight",
    "name"
   ],
   "def": "PACKED LIGHT"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "sky",
    "packedlight",
    "flavor"
   ],
   "def": "the dream ledger rides in the front seat."
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "sky",
    "lullabythread",
    "name"
   ],
   "def": "LULLABY THREAD"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "sky",
    "lullabythread",
    "flavor"
   ],
   "def": "a spool of the old hush. it never runs out."
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "sky",
    "starcharts",
    "name"
   ],
   "def": "STAR CHARTS"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "sky",
    "starcharts",
    "flavor"
   ],
   "def": "the streak is written in the sky. the sky moves with you."
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "sky",
    "ferrytoken",
    "name"
   ],
   "def": "FERRY TOKEN"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "sky",
    "ferrytoken",
    "flavor"
   ],
   "def": "the bargemaster honors it on any river."
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "constellations",
    "littlest",
    "name"
   ],
   "def": "THE LITTLEST TOOTH"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "constellations",
    "littlest",
    "flavor"
   ],
   "def": "the first one she ever took. she kept the receipt."
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "constellations",
    "fieldmouse",
    "name"
   ],
   "def": "THE FIELD MOUSE"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "constellations",
    "fieldmouse",
    "flavor"
   ],
   "def": "madrid, remembered in six stars and an ear."
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "constellations",
    "quietloom",
    "name"
   ],
   "def": "THE QUIET LOOM"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "constellations",
    "quietloom",
    "flavor"
   ],
   "def": "the hush, woven big enough to see from anywhere."
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "constellations",
    "ferryman",
    "name"
   ],
   "def": "THE FERRYMAN"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "constellations",
    "ferryman",
    "flavor"
   ],
   "def": "a different river every town. same hat."
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "constellations",
    "toothfairy",
    "name"
   ],
   "def": "THE TOOTH FAIRY"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "constellations",
    "toothfairy",
    "flavor"
   ],
   "def": "her. up there. finally on the ledger's cover."
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "hoard",
    "sack"
   ],
   "def": "a little sack"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "hoard",
    "jars"
   ],
   "def": "the jars"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "hoard",
    "chests"
   ],
   "def": "the chests"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "hoard",
    "piles"
   ],
   "def": "piles and piles"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "hoard",
    "warehouses"
   ],
   "def": "the warehouses"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "hoard",
    "silos"
   ],
   "def": "the silo fields"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "hoard",
    "mountains"
   ],
   "def": "the white mountains"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "hoard",
    "moons"
   ],
   "def": "the borrowed moons"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "loom",
    "name"
   ],
   "def": "LULLABY LOOM"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "loom",
    "flavor"
   ],
   "def": "weaves a hush you can stack."
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "multName"
   ],
   "def": "apiece"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "multNames",
    "scout"
   ],
   "def": "SCOUT GOGGLES"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "multNames",
    "mouse"
   ],
   "def": "MOUSE MAPS"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "multNames",
    "bunny"
   ],
   "def": "BROOM DODGING"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "multNames",
    "sprite"
   ],
   "def": "BRIGHTER WICKS"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "multNames",
    "phantom"
   ],
   "def": "DEEPER SILENCE"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "multNames",
    "owl"
   ],
   "def": "WIDER EYES"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "multNames",
    "ferry"
   ],
   "def": "SECOND DECK"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "multNames",
    "barge"
   ],
   "def": "DEEPER HOLD"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "multNames",
    "pact"
   ],
   "def": "PHONE TREE"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "multNames",
    "ministry"
   ],
   "def": "ANNEX WING"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "multNames",
    "starwrights"
   ],
   "def": "TALLER LADDER"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "verbs",
    "tiptoe"
   ],
   "def": "TIPTOE"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "verbs",
    "readNote"
   ],
   "def": "READ A NOTE"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "tabs",
    "tonight"
   ],
   "def": "tonight"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "tabs",
    "log"
   ],
   "def": "the log"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "tabs",
    "roost"
   ],
   "def": "the roost"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "tabs",
    "sky"
   ],
   "def": "the sky"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "meters",
    "teeth"
   ],
   "def": "TEETH"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "meters",
    "notes"
   ],
   "def": "notes"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "meters",
    "belief"
   ],
   "def": "BELIEF"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "meters",
    "stir"
   ],
   "def": "STIR"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "meters",
    "noise"
   ],
   "def": "noise"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "meters",
    "hush"
   ],
   "def": "hush"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "meters",
    "perSec"
   ],
   "def": "/s"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "ui",
    "buy"
   ],
   "def": "gather"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "ui",
    "level"
   ],
   "def": "lv"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "ui",
    "owned"
   ],
   "def": "roaming"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "ui",
    "cost"
   ],
   "def": "costs"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "ui",
    "offlineTitle"
   ],
   "def": "while you were gone"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "ui",
    "offlineButton"
   ],
   "def": "good work everyone"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "ui",
    "settings"
   ],
   "def": "settings"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "ui",
    "reset"
   ],
   "def": "forget everything"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "ui",
    "resetConfirm"
   ],
   "def": "type FORGET to confirm"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "ui",
    "exportSave"
   ],
   "def": "copy the night"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "ui",
    "importSave"
   ],
   "def": "restore a night"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "ui",
    "mute"
   ],
   "def": "hush the sounds"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "ui",
    "endingContinue"
   ],
   "def": "the sky keeps filling"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "ui",
    "wakeAside"
   ],
   "def": "someone woke. belief slips. {unit} lies low."
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "ui",
    "boardTitle"
   ],
   "def": "tonight’s jobs"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "ui",
    "boardHint"
   ],
   "def": "pick one. it resolves by dawn. finished pays; a streak pays more."
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "ui",
    "pays"
   ],
   "def": "pays: "
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "ui",
    "goalGather"
   ],
   "def": "goal: {n} teeth gathered tonight"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "ui",
    "goalNotes"
   ],
   "def": "goal: read {n} notes tonight"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "ui",
    "goalTiptoes"
   ],
   "def": "goal: tiptoe {n} times tonight"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "ui",
    "goalQuiet"
   ],
   "def": "goal: no wakes, all night (judged at dawn)"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "ui",
    "goalCalm"
   ],
   "def": "goal: stir under {n} at dawn"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "ui",
    "roostNew"
   ],
   "def": "new at the roost — "
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "ui",
    "morningTitle"
   ],
   "def": "the morning after night {n}"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "ui",
    "duskIn"
   ],
   "def": "dusk in about {m} min"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "ui",
    "dawnSoon"
   ],
   "def": "dawn soon"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "ui",
    "depart"
   ],
   "def": "another town"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "ui",
    "departConfirm"
   ],
   "def": "leave for good?"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "ui",
    "townLabel"
   ],
   "def": "town"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "ui",
    "starsLabel"
   ],
   "def": "★ earned"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "ui",
    "trace"
   ],
   "def": "trace a star"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "ui",
    "notesKept"
   ],
   "def": "notes kept"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "ui",
    "kitTitle"
   ],
   "def": "the kit — what you own"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "playtest",
    "title"
   ],
   "def": "playtest feedback"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "playtest",
    "session"
   ],
   "def": "session "
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "playtest",
    "entries"
   ],
   "def": " entries"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "playtest",
    "submit"
   ],
   "def": "submit session"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "playtest",
    "voiceHeading"
   ],
   "def": "voice"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "playtest",
    "textHeading"
   ],
   "def": "text"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "playtest",
    "record"
   ],
   "def": "● record"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "playtest",
    "stopSubmit"
   ],
   "def": "■ stop & submit"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "playtest",
    "cancel"
   ],
   "def": "cancel"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "playtest",
    "noMic"
   ],
   "def": "voice recording is not supported in this browser."
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "playtest",
    "textPlaceholder"
   ],
   "def": "type feedback…"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "playtest",
    "textSubmit"
   ],
   "def": "submit"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "playtest",
    "queueEmpty"
   ],
   "def": "nothing queued yet."
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "playtest",
    "delete"
   ],
   "def": "delete"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "playtest",
    "deleteConfirm"
   ],
   "def": "delete?"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "playtest",
    "deleteYes"
   ],
   "def": "yes"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "playtest",
    "deleteNo"
   ],
   "def": "no"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "playtest",
    "newSession"
   ],
   "def": "new session"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "playtest",
    "newSessionConfirm"
   ],
   "def": "end session and start a new one?"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "playtest",
    "newSessionYes"
   ],
   "def": "yes"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "playtest",
    "newSessionNo"
   ],
   "def": "no"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "playtest",
    "edited"
   ],
   "def": "edited"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "playtest",
    "statusSubmitting"
   ],
   "def": "submitting…"
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "playtest",
    "statusDone"
   ],
   "def": "submitted."
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "playtest",
    "statusError"
   ],
   "def": "submit failed: "
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "playtest",
    "narrowNote"
   ],
   "def": "this panel is built for a desktop-width window."
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "tips",
    "belief"
   ],
   "def": "belief scales every tooth: ×0.5 at 0, ×1.5 at 100. quiet productive nights and notes raise it. wakes cut it."
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "tips",
    "stir"
   ],
   "def": "noise above hush builds STIR. at 100 someone wakes: belief drops and the loudest crew hides. tiptoe halves noise; the loom raises hush."
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "tips",
    "notes"
   ],
   "def": "children leave notes while you work. reading one costs nothing and pays belief."
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "tips",
    "rate"
   ],
   "def": "teeth per second from the whole operation, everything applied."
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "tips",
    "dawn"
   ],
   "def": "the night ends when this does. at dawn the crew rests until dusk; the ledgers earn while you are away."
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "tips",
    "tiptoe"
   ],
   "def": "half speed, half noise, fifteen seconds. always allowed. never pretty."
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "tips",
    "tabTonight"
   ],
   "def": "the stage: the night, the jobs, the story."
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "tips",
    "tabLog"
   ],
   "def": "every night stamped, every memory kept."
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "tips",
    "tabRoost"
   ],
   "def": "hiring and gear. new arrivals get a dot."
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "tips",
    "board"
   ],
   "def": "pick one job per night. finish it before dawn for the reward. unfinished jobs just expire; a streak of finished ones pays a lasting bonus."
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "tips",
    "unitCard"
   ],
   "def": "gather hires one. max hires as many as the purse allows. owned count and × multipliers show by the name."
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "tips",
    "springboard"
   ],
   "def": "a one-time ×2 for every one of these you own, forever."
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "tips",
    "loom"
   ],
   "def": "each level raises hush — how much noise the night absorbs before STIR builds."
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "tips",
    "stars"
   ],
   "def": "stars are teeth taken up. each star ever earned adds +2% gathering, in every town, forever. spend them in the sky at the top of the roost."
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "tips",
    "skyCard"
   ],
   "def": "bought with stars, kept forever: this follows you to every town."
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "tips",
    "depart"
   ],
   "def": "finish here, bank the stars shown, and start a new town. the sky and its purchases carry over; everything else begins again."
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "tips",
    "tabSky"
   ],
   "def": "the figures. stars traced into pictures; a finished picture changes the rules for good."
  },
  {
   "tab": "Names",
   "ovKey": "names",
   "path": [
    "tips",
    "trace"
   ],
   "def": "spends one star to light the next point of this figure. the bonus lands when the figure is complete."
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "motif",
    "toothPx"
   ],
   "def": 26
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "motif",
    "stripPad"
   ],
   "def": 6
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "motif",
    "scrollPxPerS"
   ],
   "def": 8
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "motif",
    "inboundMs"
   ],
   "def": 1400
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "motif",
    "inboundMax"
   ],
   "def": 12
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "motif",
    "color"
   ],
   "def": "#7b96c9"
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "motif",
    "inboundColor"
   ],
   "def": "#a8c0ea"
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "pulse",
    "outlineMs"
   ],
   "def": 1600
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "pulse",
    "fillMs"
   ],
   "def": 260
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "pulse",
    "setFadeMs"
   ],
   "def": 700
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "floats",
    "dwellMs"
   ],
   "def": 1200
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "floats",
    "riseGap"
   ],
   "def": 18
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "floats",
    "maxConcurrent"
   ],
   "def": 3
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "beats",
    "settleMs"
   ],
   "def": 350
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "beats",
    "fadeInMs"
   ],
   "def": 450
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "beats",
    "asideMsPerChar"
   ],
   "def": 60
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "beats",
    "asideMinMs"
   ],
   "def": 2200
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "beats",
    "asideMaxMs"
   ],
   "def": 9000
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "beats",
    "whisperEveryS"
   ],
   "def": 28
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "beats",
    "whisperDwellMs"
   ],
   "def": 5200
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "ceremony",
    "dropMs"
   ],
   "def": 420
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "ceremony",
    "sparkleMs"
   ],
   "def": 900
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "ceremony",
    "flashMs"
   ],
   "def": 620
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "wake",
    "flashMs"
   ],
   "def": 900
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "sky",
    "starsMax"
   ],
   "def": 400
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "sky",
    "twinkleS"
   ],
   "def": 6
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "juice",
    "tapPop",
    "scale"
   ],
   "def": 1.12
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "juice",
    "tapPop",
    "ms"
   ],
   "def": 110
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "juice",
    "tapGlow",
    "size"
   ],
   "def": 18
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "juice",
    "tapGlow",
    "alpha"
   ],
   "def": 0.5
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "juice",
    "tapGlow",
    "ms"
   ],
   "def": 260
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "juice",
    "tapSparks",
    "count"
   ],
   "def": 6
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "juice",
    "tapSparks",
    "size"
   ],
   "def": 2.2
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "juice",
    "tapSparks",
    "spreadPx"
   ],
   "def": 34
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "juice",
    "tapSparks",
    "lifeMs"
   ],
   "def": 420
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "juice",
    "inbound",
    "glowSize"
   ],
   "def": 10
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "juice",
    "inbound",
    "glowAlpha"
   ],
   "def": 0.35
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "juice",
    "inbound",
    "trailPerS"
   ],
   "def": 14
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "juice",
    "inbound",
    "trailLife"
   ],
   "def": 500
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "juice",
    "landSparks",
    "count"
   ],
   "def": 5
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "juice",
    "landSparks",
    "size"
   ],
   "def": 2
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "juice",
    "landSparks",
    "lifeMs"
   ],
   "def": 380
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "juice",
    "buySweep",
    "alpha"
   ],
   "def": 0.22
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "juice",
    "buySweep",
    "ms"
   ],
   "def": 700
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "juice",
    "ramp",
    "rateLo"
   ],
   "def": 10
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "juice",
    "ramp",
    "rateHi"
   ],
   "def": 1000000000
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "juice",
    "ramp",
    "sizeHi"
   ],
   "def": 1.6
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "juice",
    "ramp",
    "glowHi"
   ],
   "def": 1.8
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "juice",
    "ramp",
    "trailHi"
   ],
   "def": 2.5
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "juice",
    "ramp",
    "scrollHi"
   ],
   "def": 3
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "hoard",
    "alpha"
   ],
   "def": 0.5
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "hoard",
    "glintPerS"
   ],
   "def": 0.8
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "hoard",
    "centerGapPx"
   ],
   "def": 72
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "hoard",
    "stageScale"
   ],
   "def": 2.4
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "hoard",
    "stageAlpha"
   ],
   "def": 0.33
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "palettes",
    "0",
    "bg"
   ],
   "def": "#10131c"
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "palettes",
    "0",
    "surface"
   ],
   "def": "#171b27"
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "palettes",
    "0",
    "ink"
   ],
   "def": "#d7dceb"
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "palettes",
    "0",
    "dim"
   ],
   "def": "#8b93ad"
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "palettes",
    "0",
    "accent"
   ],
   "def": "#7b96c9"
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "palettes",
    "0",
    "glow"
   ],
   "def": "#a8c0ea"
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "palettes",
    "1",
    "bg"
   ],
   "def": "#0e1220"
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "palettes",
    "1",
    "surface"
   ],
   "def": "#151a2b"
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "palettes",
    "1",
    "ink"
   ],
   "def": "#dde2f0"
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "palettes",
    "1",
    "dim"
   ],
   "def": "#8f97b2"
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "palettes",
    "1",
    "accent"
   ],
   "def": "#84a1d8"
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "palettes",
    "1",
    "glow"
   ],
   "def": "#b4cbf2"
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "palettes",
    "2",
    "bg"
   ],
   "def": "#0b0f1e"
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "palettes",
    "2",
    "surface"
   ],
   "def": "#12172a"
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "palettes",
    "2",
    "ink"
   ],
   "def": "#e2e6f3"
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "palettes",
    "2",
    "dim"
   ],
   "def": "#939bb6"
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "palettes",
    "2",
    "accent"
   ],
   "def": "#8ba8de"
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "palettes",
    "2",
    "glow"
   ],
   "def": "#bfd4f7"
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "palettes",
    "3",
    "bg"
   ],
   "def": "#080c1c"
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "palettes",
    "3",
    "surface"
   ],
   "def": "#101527"
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "palettes",
    "3",
    "ink"
   ],
   "def": "#e8ecf7"
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "palettes",
    "3",
    "dim"
   ],
   "def": "#98a0bb"
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "palettes",
    "3",
    "accent"
   ],
   "def": "#93b0e4"
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "palettes",
    "3",
    "glow"
   ],
   "def": "#ccdefc"
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "palettes",
    "25",
    "bg"
   ],
   "def": "#081420"
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "palettes",
    "25",
    "surface"
   ],
   "def": "#0e1b2b"
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "palettes",
    "25",
    "ink"
   ],
   "def": "#dfeaf2"
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "palettes",
    "25",
    "dim"
   ],
   "def": "#8fa3b4"
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "palettes",
    "25",
    "accent"
   ],
   "def": "#7fb0c9"
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "palettes",
    "25",
    "glow"
   ],
   "def": "#b8e0ef"
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "sound",
    "master"
   ],
   "def": 0.5
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "sound",
    "tap"
   ],
   "def": 0.06
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "sound",
    "fill"
   ],
   "def": 0.03
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "sound",
    "beat"
   ],
   "def": 0.035
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "sound",
    "buy"
   ],
   "def": 0.03
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "sound",
    "wake"
   ],
   "def": 0.05
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "sound",
    "note"
   ],
   "def": 0.03
  },
  {
   "tab": "VFX",
   "ovKey": "vfx",
   "path": [
    "sound",
    "press"
   ],
   "def": 0.04
  },
  {
   "tab": "Workshop",
   "ovKey": "vfx",
   "path": [
    "juice",
    "tapPop",
    "scale"
   ],
   "def": 1.12,
   "min": 0.9,
   "max": 1.8
  },
  {
   "tab": "Workshop",
   "ovKey": "vfx",
   "path": [
    "juice",
    "tapPop",
    "ms"
   ],
   "def": 110,
   "min": 40,
   "max": 500
  },
  {
   "tab": "Workshop",
   "ovKey": "vfx",
   "path": [
    "juice",
    "tapGlow",
    "size"
   ],
   "def": 18,
   "min": 0,
   "max": 60
  },
  {
   "tab": "Workshop",
   "ovKey": "vfx",
   "path": [
    "juice",
    "tapGlow",
    "alpha"
   ],
   "def": 0.5,
   "min": 0,
   "max": 1
  },
  {
   "tab": "Workshop",
   "ovKey": "vfx",
   "path": [
    "juice",
    "tapGlow",
    "ms"
   ],
   "def": 260,
   "min": 60,
   "max": 1200
  },
  {
   "tab": "Workshop",
   "ovKey": "vfx",
   "path": [
    "juice",
    "tapSparks",
    "count"
   ],
   "def": 6,
   "min": 0,
   "max": 40
  },
  {
   "tab": "Workshop",
   "ovKey": "vfx",
   "path": [
    "juice",
    "tapSparks",
    "size"
   ],
   "def": 2.2,
   "min": 0.5,
   "max": 8
  },
  {
   "tab": "Workshop",
   "ovKey": "vfx",
   "path": [
    "juice",
    "tapSparks",
    "spreadPx"
   ],
   "def": 34,
   "min": 6,
   "max": 120
  },
  {
   "tab": "Workshop",
   "ovKey": "vfx",
   "path": [
    "juice",
    "tapSparks",
    "lifeMs"
   ],
   "def": 420,
   "min": 100,
   "max": 2000
  },
  {
   "tab": "Workshop",
   "ovKey": "vfx",
   "path": [
    "juice",
    "inbound",
    "glowSize"
   ],
   "def": 10,
   "min": 0,
   "max": 40
  },
  {
   "tab": "Workshop",
   "ovKey": "vfx",
   "path": [
    "juice",
    "inbound",
    "glowAlpha"
   ],
   "def": 0.35,
   "min": 0,
   "max": 1
  },
  {
   "tab": "Workshop",
   "ovKey": "vfx",
   "path": [
    "juice",
    "inbound",
    "trailPerS"
   ],
   "def": 14,
   "min": 0,
   "max": 60
  },
  {
   "tab": "Workshop",
   "ovKey": "vfx",
   "path": [
    "juice",
    "inbound",
    "trailLife"
   ],
   "def": 500,
   "min": 100,
   "max": 2000
  },
  {
   "tab": "Workshop",
   "ovKey": "vfx",
   "path": [
    "juice",
    "landSparks",
    "count"
   ],
   "def": 5,
   "min": 0,
   "max": 40
  },
  {
   "tab": "Workshop",
   "ovKey": "vfx",
   "path": [
    "juice",
    "landSparks",
    "size"
   ],
   "def": 2,
   "min": 0.5,
   "max": 8
  },
  {
   "tab": "Workshop",
   "ovKey": "vfx",
   "path": [
    "juice",
    "landSparks",
    "lifeMs"
   ],
   "def": 380,
   "min": 100,
   "max": 2000
  },
  {
   "tab": "Workshop",
   "ovKey": "vfx",
   "path": [
    "juice",
    "buySweep",
    "alpha"
   ],
   "def": 0.22,
   "min": 0,
   "max": 1
  },
  {
   "tab": "Workshop",
   "ovKey": "vfx",
   "path": [
    "juice",
    "buySweep",
    "ms"
   ],
   "def": 700,
   "min": 200,
   "max": 2500
  },
  {
   "tab": "Workshop",
   "ovKey": "vfx",
   "path": [
    "juice",
    "ramp",
    "rateLo"
   ],
   "def": 10,
   "min": 1,
   "max": 10000
  },
  {
   "tab": "Workshop",
   "ovKey": "vfx",
   "path": [
    "juice",
    "ramp",
    "rateHi"
   ],
   "def": 1000000000,
   "min": 1000000,
   "max": 1000000000000
  },
  {
   "tab": "Workshop",
   "ovKey": "vfx",
   "path": [
    "juice",
    "ramp",
    "sizeHi"
   ],
   "def": 1.6,
   "min": 1,
   "max": 4
  },
  {
   "tab": "Workshop",
   "ovKey": "vfx",
   "path": [
    "juice",
    "ramp",
    "glowHi"
   ],
   "def": 1.8,
   "min": 1,
   "max": 6
  },
  {
   "tab": "Workshop",
   "ovKey": "vfx",
   "path": [
    "juice",
    "ramp",
    "trailHi"
   ],
   "def": 2.5,
   "min": 1,
   "max": 8
  },
  {
   "tab": "Workshop",
   "ovKey": "vfx",
   "path": [
    "juice",
    "ramp",
    "scrollHi"
   ],
   "def": 3,
   "min": 1,
   "max": 10
  },
  {
   "tab": "Hoard",
   "ovKey": "vfx",
   "path": [
    "hoard",
    "alpha"
   ],
   "def": 0.5,
   "min": 0,
   "max": 1
  },
  {
   "tab": "Hoard",
   "ovKey": "vfx",
   "path": [
    "hoard",
    "glintPerS"
   ],
   "def": 0.8,
   "min": 0,
   "max": 10
  },
  {
   "tab": "Hoard",
   "ovKey": "vfx",
   "path": [
    "hoard",
    "centerGapPx"
   ],
   "def": 72,
   "min": 40,
   "max": 160
  },
  {
   "tab": "Hoard",
   "ovKey": "vfx",
   "path": [
    "hoard",
    "stageScale"
   ],
   "def": 2.4,
   "min": 0.5,
   "max": 5
  },
  {
   "tab": "Hoard",
   "ovKey": "vfx",
   "path": [
    "hoard",
    "stageAlpha"
   ],
   "def": 0.33,
   "min": 0,
   "max": 1
  }
 ]
};
