// The story. Pure data: no imports, no DOM, no functions in records.
// Registers: 'memory' (the fairy, lowercase, spare) · 'ledger' (fae bureaucracy,
// mono, counted) · responses are the player's voice (lowercase snark).
// Trigger types: start · afterBeat{id} · outline{set} · lifetime{value,minAct?} ·
// buy{unit,count} · upgrade{id} · loom{level} · wake{count} · noteRead{count} ·
// taps{count} · tiptoes{count} · night{count} · sailings{count} · stirReveal ·
// ending · never
// A beat pauses the game until its response is pressed. Beats never fire offline.

export const SCRIPT_DEFAULTS = Object.freeze({
  beats: [
    // ---- ACT 0 · WHAT (opening, per original spec, verbatim where quoted) ----
    { id: 'a0-icon',  act: 0, register: 'memory', stage: 'icon', maxTown: 1, text: '',
      response: 'what', trigger: { type: 'start' } },
    { id: 'a0-few',   act: 0, register: 'memory', stage: 'few', maxTown: 1, text: '',
      response: 'what the', trigger: { type: 'afterBeat', id: 'a0-icon' } },
    { id: 'a0-pile',  act: 0, register: 'memory', stage: 'pile', maxTown: 1, text: '',
      response: '...', trigger: { type: 'afterBeat', id: 'a0-few' } },
    { id: 'a0-why',   act: 0, register: 'memory', maxTown: 1, text: '...teeth...',
      response: 'why do i want teeth', trigger: { type: 'afterBeat', id: 'a0-pile' },
      effects: { showTap: true } },
    { id: 'a0-fairy', act: 0, register: 'memory', maxTown: 1, text: 'fairy.',
      response: 'alright', trigger: { type: 'outline', set: 3 } },
    { id: 'a0-toothfairy', act: 0, register: 'memory', maxTown: 1, text: 'TOOTH. fairy.',
      response: 'yeah ok', trigger: { type: 'afterBeat', id: 'a0-fairy' } },
    { id: 'a0-getteeth', act: 0, register: 'memory', maxTown: 1, text: "Let's get some TEETH.",
      response: 'hell yeah', trigger: { type: 'afterBeat', id: 'a0-toothfairy' },
      effects: { act: 1 } },

    // ---- TOWN 2+ (the arrival replaces the amnesia opening) ----
    { id: 't2-arrive', act: 1, register: 'memory', minTown: 2,
      text: 'another town. smaller. the moon followed me here. i remembered my name the whole way.',
      response: 'back to work', trigger: { type: 'start' } },
    { id: 't2-ledger', act: 1, register: 'ledger', minTown: 2,
      text: 'transfer approved. balance carried: see the sky. the rounds resume at dusk. welcome, again.',
      response: 'again.', trigger: { type: 'afterBeat', id: 't2-arrive' } },

    // ---- ACT 1 · THE ROUNDS ----
    { id: 'a1-babyfae', act: 1, register: 'memory',
      text: "there's a small one following me now. she has my eyes. one of them, anyway.",
      response: 'she can stay', trigger: { type: 'upgrade', id: 'babyfae' } },
    { id: 'a1-wings', act: 1, register: 'memory',
      text: 'wings. i had— have. wings. and apparently... staff.',
      response: 'good for you', trigger: { type: 'buy', unit: 'scout', count: 1 } },
    { id: 'a1-rounds', act: 1, register: 'memory',
      text: 'the rounds. that was the word. you do the rounds, you check the pillows, you keep the ledger.',
      response: 'the ledger?', trigger: { type: 'buy', unit: 'scout', count: 5 } },
    { id: 'a1-protocol', act: 1, register: 'memory',
      text: "pillow protocol: lift, don't slide. a slide makes a sound. a sound makes a morning.",
      response: 'noted', trigger: { type: 'lifetime', value: 300 } },
    { id: 'a1-coin', act: 1, register: 'memory',
      text: "you're supposed to leave something. a coin. i left a button once. she kept it. they keep everything.",
      response: 'classy', trigger: { type: 'lifetime', value: 800 } },
    { id: 'a1-notes', act: 1, register: 'memory',
      text: "they leave notes. 'dear tooth fairy.' i can't read them yet. i will.",
      response: 'why not', trigger: { type: 'lifetime', value: 1500 } },
    { id: 'a1-flashlight', act: 1, register: 'memory',
      text: 'one of them sleeps with a flashlight under the pillow. waiting for me. i like that one.',
      response: 'keep an eye on that one', trigger: { type: 'lifetime', value: 2500 } },
    { id: 'a1-mouse', act: 1, register: 'memory',
      text: "the mouse. from madrid. we worked the coasts together, before. she asks if i remember lisbon. i don't. she says good.",
      response: 'very professional', trigger: { type: 'buy', unit: 'mouse', count: 1 } },
    { id: 'a1-knock', act: 1, register: 'memory',
      text: "you tap like you're knocking. politely. on a hundred tiny doors.",
      response: 'someone has to', trigger: { type: 'taps', count: 250 } },

    // ---- ACT 2 · THE OPERATION ----
    { id: 'a2-bunny', act: 2, register: 'memory',
      text: 'the dust bunnies were always here. under every bed. listening. they\'d like dental now, and a name each.',
      response: 'granted', trigger: { type: 'buy', unit: 'bunny', count: 1 } },
    { id: 'a2-owl', act: 2, register: 'memory',
      text: 'the owl took the job without asking what it pays. it says it has seen the tall one in the doorway before. years ago. watching, even then.',
      response: 'noted. unsettling.', trigger: { type: 'buy', unit: 'owl', count: 1 } },
    { id: 'a2-stir', act: 2, register: 'memory',
      text: 'the houses are starting to stir. we are many now, and many is loud.',
      response: 'hush then', trigger: { type: 'stirReveal' }, effects: { act: 2 } },
    { id: 'a2-tiptoe', act: 2, register: 'memory',
      text: "i can tiptoe. we all can. it's slow and it's humiliating and it works.",
      response: 'tiptoe it is', trigger: { type: 'afterBeat', id: 'a2-stir' },
      effects: { revealTiptoe: true } },
    { id: 'a2-hush', act: 2, register: 'ledger',
      text: 'advisory 7-c, plain version. noise is how loud the crew works. hush is how much the night absorbs. when noise is higher than hush, the STIR meter climbs. at 100, a child wakes: belief −10, and your loudest crew hides for a while. TIPTOE halves noise for a bit. the loom raises hush. keep noise under hush and STIR falls on its own.',
      response: 'noted, ominously', trigger: { type: 'afterBeat', id: 'a2-tiptoe' } },
    { id: 'a2-night', act: 2, register: 'memory',
      text: "the night has edges now. i can feel the dawn coming like a tide. when it comes, we rest — the ledgers work while we sleep, if you've bought the right one.",
      response: 'set the clock', trigger: { type: 'afterBeat', id: 'a2-hush' },
      effects: { revealNight: true } },
    { id: 'a2-firstwake', act: 2, register: 'memory',
      text: 'the flashlight. i knew it would be the flashlight. small beam, big eyes. we regarded each other. i took the tooth anyway.',
      response: 'professional', trigger: { type: 'wake', count: 1 } },
    { id: 'a2-loom', act: 2, register: 'memory',
      text: 'the loom hums under the floorboards. the houses sleep deeper. the needles know a lullaby i almost remember.',
      response: 'almost?', trigger: { type: 'loom', level: 1 } },
    { id: 'a2-sprite', act: 2, register: 'memory',
      text: "the mayflies clock in knowing. ninety seconds of forever, they call it. i don't watch the end.",
      response: 'grim little guys', trigger: { type: 'buy', unit: 'sprite', count: 1 } },
    { id: 'a2-afterglow', act: 2, register: 'memory',
      text: 'now when they go, they go like sparklers. they asked for this. in writing.',
      response: 'in writing??', trigger: { type: 'upgrade', id: 'afterglow' } },
    { id: 'a2-ferry', act: 2, register: 'memory',
      text: 'yes. it is a ferry for teeth. the river was already there, which raises questions i am not asking.',
      response: 'fair enough', trigger: { type: 'buy', unit: 'ferry', count: 1 } },
    { id: 'a2-firstnote', act: 2, register: 'memory',
      text: "'dear tooth fairy. i know it's you. i won't tell.' ...huh.",
      response: 'kids are alright', trigger: { type: 'noteRead', count: 1 } },
    { id: 'a2-phantom', act: 2, register: 'memory',
      text: "the phantom doesn't speak. it left a card. the card says 'noise is a choice.' unsettling. effective.",
      response: 'hire more', trigger: { type: 'buy', unit: 'phantom', count: 1 } },
    { id: 'a2-wake3', act: 2, register: 'memory',
      text: "three wakes now. word travels between pillows. they're organizing. sentries in pajamas, shifts and everything.",
      response: 'adorable. bad.', trigger: { type: 'wake', count: 3 } },
    { id: 'a2-notes5', act: 2, register: 'memory',
      text: 'i can read them now. all of them. i keep the good ones tucked in my left wing. it drags a little.',
      response: 'worth it', trigger: { type: 'noteRead', count: 5 } },
    { id: 'a2-loom3', act: 2, register: 'memory',
      text: 'three looms deep, the hush has a texture. like snowfall indoors. a scout fell asleep standing up. docked pay. tucked in.',
      response: 'both fair', trigger: { type: 'loom', level: 3 } },
    { id: 'a2-spire', act: 2, register: 'memory',
      text: 'i watched the town from the church spire tonight. every window a job. every job a kid. i used to know all their names. the ledger knows them now.',
      response: 'the ledger remembers', trigger: { type: 'lifetime', value: 100000, minAct: 2 } },
    // ---- ACT 2.5 · THE RIVER ----
    { id: 'r-enter', act: 2, register: 'memory',
      text: 'i rode the ferry tonight. all the way. past the last house, into the fog. there is a far shore. i have been there. i cannot remember it.',
      response: 'ride again', trigger: { type: 'lifetime', value: 800000, minAct: 2 },
      effects: { act: 25 } },
    { id: 'r-barge', act: 25, register: 'memory',
      text: 'the bargemaster tips her hat like we have met. we have met. the hold smells like rain and enamel.',
      response: 'load it up', trigger: { type: 'buy', unit: 'barge', count: 1 } },
    { id: 'r-firstsail', act: 25, register: 'memory',
      text: 'first sailing on the books. the barge came back low in the water and heavier than it left. the river pays interest. rivers should not do that.',
      response: 'rivers keep secrets', trigger: { type: 'sailings', count: 1 } },
    { id: 'r-fog', act: 25, register: 'memory',
      text: 'third night on the river. the fog has a shape in it now. tall. patient. it waves back.',
      response: '...wave again', trigger: { type: 'sailings', count: 3 } },
    { id: 'r-ledger', act: 25, register: 'ledger',
      text: 'river manifest audited. sailings: 5. shrinkage: zero. the far shore signs its receipts in a hand you would recognize.',
      response: 'i might', trigger: { type: 'sailings', count: 5 } },
    { id: 'r-doorway', act: 25, register: 'memory',
      text: "there's someone in the doorway. tall. tired. holding a tooth between finger and thumb like it's evidence. they're not surprised to see me. they smell like the river.",
      response: 'uh oh', trigger: { type: 'lifetime', value: 8000000, minAct: 25 },
      effects: { act: 3 } },

    // ---- ACT 3 · THE FOLD ----
    { id: 'a3-fold', act: 3, register: 'memory',
      text: "they've known. of course they've known. who did i think moved the pillow back? who left the porch light off on purpose?",
      response: 'the parents', trigger: { type: 'afterBeat', id: 'r-doorway' } },
    { id: 'a3-firstpact', act: 3, register: 'memory',
      text: "the first signature is neat. careful. grown-up. they kept the flashlight, you know. it's on the nightstand now. for their kid.",
      response: 'oh.', trigger: { type: 'buy', unit: 'pact', count: 1 } },
    { id: 'a3-ledger', act: 3, register: 'ledger',
      text: 'pact registered. houses: 3. stir: falling. the ministry sends its regards and form 32-b.',
      response: 'bureaucracy!', trigger: { type: 'buy', unit: 'pact', count: 3 } },
    { id: 'a3-phonetree', act: 3, register: 'memory',
      text: "they have a phone tree. they had it before phones. i don't ask what it was a tree of.",
      response: "don't ask", trigger: { type: 'buy', unit: 'pact', count: 5 } },
    { id: 'a3-ministry', act: 3, register: 'memory',
      text: "the ministry always existed. i just kept losing the door. it's behind the coats. it was always behind the coats.",
      response: 'naturally', trigger: { type: 'buy', unit: 'ministry', count: 1 } },
    { id: 'a3-starwrights', act: 3, register: 'memory',
      text: "the starwrights don't gather teeth. they take them up. i asked up where. they pointed. i didn't ask again.",
      response: 'up.', trigger: { type: 'buy', unit: 'starwrights', count: 1 } },
    { id: 'a3-almost', act: 3, register: 'memory',
      text: "i'm near the bottom of the ledger now. the oldest page. my handwriting, but smaller. a name i almost say out loud.",
      response: '...', trigger: { type: 'lifetime', value: 200000000, minAct: 3 } },
    { id: 'a3-firstpage', act: 3, register: 'memory',
      text: 'found it. the first entry. one tooth. one coin. one kid who grew up and — oh. oh. that is who signs the pacts now.',
      response: 'full circle', trigger: { type: 'lifetime', value: 800000000, minAct: 3 } },

    // ---- ENDING ----
    { id: 'end-remember', act: 3, register: 'memory',
      text: "i remember what they're for now. come see.",
      response: 'show me', trigger: { type: 'ending' }, effects: { ending: true } },
    { id: 'end-sky', act: 3, register: 'memory',
      text: 'every tooth becomes a star. it always did. the sky is the ledger, and the ledger is full of children who grew up brave enough to lose things. keep going. there is room.',
      response: 'keep going', trigger: { type: 'afterBeat', id: 'end-remember' },
      effects: { postEnd: true } },

    { id: 'end-town', act: 3, register: 'memory',
      text: 'there is another town. there is always another town. the stars come with me — they always did.',
      response: 'pack up', trigger: { type: 'afterBeat', id: 'end-sky' } },

    // ---- THE SKY (constellations, town 2+) ----
    { id: 'sky-trace', act: 1, register: 'memory', minTown: 2,
      text: 'i put two stars next to each other and the night held them there. a picture. mine.',
      response: 'keep going', trigger: { type: 'trace', count: 1 } },
    { id: 'sky-figure', act: 1, register: 'ledger', minTown: 2,
      text: 'figure received and recorded. the sky accepts the entry. permanence granted, form C-1.',
      response: 'permanence.', trigger: { type: 'figure', count: 1 } },

    // ---- MIGRATION ----
    { id: 'mig-nights', act: 1, register: 'memory',
      text: 'the nights have gotten longer. i can feel the dawn now, and the rest between. the work is the same. there is just more night to do it in.',
      response: 'more night. got it.', trigger: { type: 'never' },
      effects: { revealNight: true } },
  ],

  // One-shot stage asides: non-pausing, fade after a beat's read time.
  asides: [
    { id: 'as-bunny10', trigger: { type: 'buy', unit: 'bunny', count: 10 },
      text: 'the bunnies have names now. all of them are gerald.' },
    { id: 'as-owl5', trigger: { type: 'buy', unit: 'owl', count: 5 },
      text: 'five owls. the attic minutes are exhaustive.' },
    { id: 'as-starwrights3', trigger: { type: 'buy', unit: 'starwrights', count: 3 },
      text: 'three crews on the ladder. the sky takes deliveries now.' },
    { id: 'as-scout2',  trigger: { type: 'buy', unit: 'scout', count: 2 },
      text: 'two of them compare socks.' },
    { id: 'as-scout10', trigger: { type: 'buy', unit: 'scout', count: 10 },
      text: 'the scouts have a union now. their demands are reasonable.' },
    { id: 'as-scout20', trigger: { type: 'buy', unit: 'scout', count: 20 },
      text: 'the scouts hold a jamboree. attendance: mandatory. fun: also mandatory.' },
    { id: 'as-mouse5',  trigger: { type: 'buy', unit: 'mouse', count: 5 },
      text: 'the mice have opinions about the scouts.' },
    { id: 'as-sprite10', trigger: { type: 'buy', unit: 'sprite', count: 10 },
      text: 'the mayflies hold tiny retirement parties. constantly.' },
    { id: 'as-ferry5',  trigger: { type: 'buy', unit: 'ferry', count: 5 },
      text: 'the ferries form a modest armada. the river copes.' },
    { id: 'as-tap1000', trigger: { type: 'taps', count: 1000 },
      text: 'your tapping finger has developed a reputation.' },
    { id: 'as-tiptoe3', trigger: { type: 'tiptoes', count: 3 },
      text: 'you are getting good at the humiliating part.' },
    { id: 'as-mouse15', trigger: { type: 'buy', unit: 'mouse', count: 15 },
      text: 'the mice unionize with the scouts. joint sock committee.' },
    { id: 'as-phantom5', trigger: { type: 'buy', unit: 'phantom', count: 5 },
      text: 'five phantoms. the quiet has staff now.' },
    { id: 'as-sprite25', trigger: { type: 'buy', unit: 'sprite', count: 25 },
      text: 'the retirement parties have a band now. tiny. loud for their size.' },
    { id: 'as-pact5', trigger: { type: 'buy', unit: 'pact', count: 5 },
      text: 'five households signed. the phone tree blooms.' },
    { id: 'as-ministry2', trigger: { type: 'buy', unit: 'ministry', count: 2 },
      text: 'the annex has an annex.' },
    { id: 'as-tap5000', trigger: { type: 'taps', count: 5000 },
      text: 'the finger is legend. children speak of the knock.' },
    { id: 'as-notes10', trigger: { type: 'noteRead', count: 10 },
      text: 'you keep every note. somewhere, a drawer strains.' },
    { id: 'as-wake5', trigger: { type: 'wake', count: 5 },
      text: 'the pajama sentries have a rota now. you respect it.' },
    { id: 'as-town3', minTown: 3, maxTown: 3, trigger: { type: 'start' },
      text: 'the bargemaster waves from a different river. same hat.' },
    { id: 'as-sky-all', minTown: 2, trigger: { type: 'figure', count: 5 },
      text: 'the sky is full of pictures now. every town i ever left is looking up at the same ones.' },
  ],

  // Idle whispers: ambient stage lines, per act. Small pools, no filler.
  whispers: {
    1: ['a window, unlatched, on purpose.',
        'somewhere a molar wiggles.',
        'sock. sock. sock. tooth.',
        'the moon keeps minutes.',
        'a coin, warm from a pocket.',
        'the ledger turns a page by itself.'],
    2: ['the houses breathe slow.',
        'a nightlight negotiates with the dark.',
        'a horn on the river, one town over. softly.',
        'small wings, punching in.',
        'the loom hums a bar of something old.',
        'a mayfly clocks out, waving.'],
    25: ['a horn, closer tonight.',
         'the water holds its breath.',
         'rope, wet wood, and mint.',
         'the far shore keeps a light on.',
         'something upriver is counting too.'],
    3: ['something rustles, house to house.',
        'a porch light goes dark, politely.',
        'paperwork, in triplicate, somewhere.',
        'the sky is patient.',
        'behind the coats, a light under a door.',
        'the first page waits.'],
  },

  // Notes the children leave. READ A NOTE shows the next one; recycles.
  notes: [
    "dear tooth fairy. i know it's you. i won't tell.",
    'dear tooth fairy. this one has a filling. sorry.',
    "dear tooth fairy. my brother says you're not real. his tooth is under his pillow. do your worst.",
    'dear tooth fairy. i pulled it myself. invoice attached.',
    'dear tooth fairy. do you take grown-up teeth? asking for my dad.',
    'dear tooth fairy. i left the window open. it gets cold. be quick.',
    'dear tooth fairy. what do you DO with them?',
    'dear tooth fairy. mom says inflation. what are you paying these days?',
    'dear tooth fairy. it is under the pillow. the OTHER pillow. good luck.',
    'dear tooth fairy. i drew you. i gave you good wings. you owe me.',
    'dear tooth fairy. grandpa put his whole teeth under the pillow. all of them. please advise.',
    'dear tooth fairy. the dog got this one first. sorry about the shape.',
    'dear tooth fairy. are you a bird? settle a bet.',
    'dear tooth fairy. i stayed up all night. i blinked once. rats.',
    'dear tooth fairy. mrs. avery put it in an envelope at school. the envelope is also for you.',
    'dear tooth fairy. my sister says you melt them into castles. build responsibly.',
    'dear tooth fairy. do the teeth miss me?',
    'dear tooth fairy. return policy?',
    'dear tooth fairy. this is my last one. make it count.',
  ],
});

// Overrides: { beats: {id: {text, response, ...}}, addedBeats: [...],
//              asides: {id: {...}}, addedAsides: [...], whispers: {act: [...]},
//              notes: [...] } — the Script tab writes only what changed.
export function buildScript(o) {
  if (!o || typeof o !== 'object') return SCRIPT_DEFAULTS;
  const patch = (list, edits, added) => {
    let out = list.map((b) => (edits && edits[b.id] ? { ...b, ...edits[b.id] } : b));
    if (edits) out = out.filter((b) => !edits[b.id] || !edits[b.id].removed);
    if (Array.isArray(added)) out = out.concat(added.filter((b) => b && b.id));
    return out;
  };
  return Object.freeze({
    beats: patch(SCRIPT_DEFAULTS.beats, o.beats, o.addedBeats),
    asides: patch(SCRIPT_DEFAULTS.asides, o.asides, o.addedAsides),
    whispers: { ...SCRIPT_DEFAULTS.whispers, ...(o.whispers || {}) },
    notes: Array.isArray(o.notes) && o.notes.length ? o.notes : SCRIPT_DEFAULTS.notes,
  });
}
